
name: Run CI 
on: [push]

jobs:
  ci:
    name: CI for MATLAB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0.1.2
        env:
          MATHWORKS_TOKEN: ${{ secrets.MATHWORKS_TOKEN }}

      - name: Run Tests
        uses: matlab-actions/run-tests@v0.1.0
        with:
          source-folder: tbx
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
