
name: Run CI 
on: [push]

jobs:
  ci:
    name: CI for MATLAB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0.1.2
        

      - name: Run Tests
        uses: matlab-actions/run-tests@feature-newoption-tests
        with:
          source-folder: tbx
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          test-results-pdf: test-results/pdf-results.pdf
          select-by-folder: ['newtests','tests']
            
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PDFt
          path: test-results/pdf-results.pdf
          
          
