
name: Run CI 
on: [push]

jobs:
  ci:
    name: CI for MATLAB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v0.1.2
        env:
          MATHWORKS_TOKEN: ${{ secrets.MATHWORKS_TOKEN }}

      - name: Run Tests
        uses: matlab-actions/run-tests@v0.1.0
        with:
          source-folder: tbx
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
            
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-artifact
          path: code-coverage/coverage.xml
          
      - name: upload to codecov 
        uses: codecov/codecov-action@v1 
        with:
          file: code-coverage/coverage.xml
          
          
      - name : Generate Junit report
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         files: test-results/results.xml
